version: '1.2.0.{build}'

environment:
  nuget_apikey:
    secure: AWSfDUQgVaMF1fhfsaVx5Hy/qIa9lwyPwXQ9kYTYUJV4qdEeFHMIggk2COOD6DH2

image: Visual Studio 2017

install:
  - ps: Install-Module InvokeBuild -Force
  - ps: Install-Module Pester -Force -SkipPublisherCheck
  - ps: Install-Module PlatyPS -Force
  - docker version

platform:
  - x64

before_build:
  - ps: |
      # Define replacements for manifest file
      $replacements = @{}

      # Update build version if tag is set
      if ( $env:APPVEYOR_REPO_TAG_NAME ) {
        $newVersion = $env:APPVEYOR_REPO_TAG_NAME
        Update-AppveyorBuild -Version $newVersion
      } else {
        $newVersion = $env:APPVEYOR_BUILD_VERSION
      }
      $replacements["ModuleVersion = '.*'"] = "ModuleVersion = '$env:APPVEYOR_BUILD_VERSION'"

      # Update manifest file
      $manifestPath = "$env:APPVEYOR_BUILD_FOLDER\src\PSDocker.psd1"
      $manifestContent = Get-Content -Path $manifestPath -Raw
      $replacements.GetEnumerator() | ForEach-Object {
        $manifestContent = $manifestContent -replace $_.Key, $_.Value
      }
      $manifestContent.Trim() | Set-Content -Path $manifestPath

      # Update docs
      Invoke-Build UpdateDocs

build_script:
  - ps: Invoke-Build Build

test_script:
  - ps: |
      $testResultsFile = ".\TestsResults.xml"
      $res = Invoke-Pester "$env:APPVEYOR_BUILD_FOLDER\src\Test" -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru
      (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))
      if ($res.FailedCount -gt 0) {
          throw "$($res.FailedCount) tests failed."
      }

# deploy on tag
deploy_script:
  - ps: |
      if ( $env:APPVEYOR_REPO_TAG_NAME ) {
        Invoke-Build Publish
      }
